services:
  air:
    container_name: app
    healthcheck:
      test: curl -fsS localhost:3000/health
    image: cosmtrek/air:v1.28.0
    ports:
      - 3000:3000
    volumes:
      - ./:/app/
    working_dir: /app

  app:
    build: .
    container_name: invoice
    depends_on:
      - db

  db:
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    image: postgres:15.3
    ports:
      - 5432:5432
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
version: '3.15'

volumes:
  data:
