services:
  air:
    container_name: app
    healthcheck:
      test: curl -fsS localhost:3000/health
    image: cosmtrek/air:v1.28.0
    ports:
      - 3000:3000
    volumes:
      - ./:/app/
    working_dir: /app

  app:
    build: .
    container_name: invoice
    env_file:
      - .env
    depends_on:
      - db

  db:
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    image: postgres
    ports:
      - ${DB_PORT}:5432
    restart: always
    volumes:
      - ./internal/infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

version: '3.15'

volumes:
  data:
